# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    # - kinova_arm_controller
    - joint_trajectory_controller

  # kinova_arm_controller:
  #   type: FollowJointTrajectory
  #   action_ns: follow_joint_trajectory
  #   default: true
  #   joints:
  #     - joint_1
  #     - joint_2
  #     - joint_3
  #     - joint_4
  #     - joint_5
  #     - joint_6
  #   action_ns: follow_joint_trajectory
  #   default: true

  joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6

