# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_state_broadcaster:
  ros__parameters:
    joints: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]


joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    command_interfaces:
      - position
    # command_joints: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]
    state_interfaces:
      - position
      # - velocity

    state_publish_rate: 10.0
    action_monitor_rate: 10.0 
    allow_partial_joints_goal: false
    open_loop_control: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0 # 0.0 means no time limit
      joint_1:
        trajectory: 0.1 # Maximum error before triggering corrective action
        goal: 0.03 # Maximum tolerable goal deviation before goal considered to be reached

      joint_2:
        trajectory: 0.1 # Maximum error before triggering corrective action
        goal: 0.03 # Maximum tolerable goal deviation before goal considered to be reached

      joint_3:
        trajectory: 0.1 # Maximum error before triggering corrective action
        goal: 0.03 # Maximum tolerable goal deviation before goal considered to be reached

      joint_4:
        trajectory: 0.1 # Maximum error before triggering corrective action
        goal: 0.03 # Maximum tolerable goal deviation before goal considered to be reached

      joint_5:
        trajectory: 0.1 # Maximum error before triggering corrective action
        goal: 0.03 # Maximum tolerable goal deviation before goal considered to be reached

      joint_6:
        trajectory: 0.1 # Maximum error before triggering corrective action
        goal: 0.03 # Maximum tolerable goal deviation before goal considered to be reached

    